### ISSUE TITLE
Use sops data source to decrypt encoded files

### ISSUE THREAD

**Issue by tonswart** [microsoft/azure-pipelines-terraform#111]
How can I use the sops data source in my terraform deployments?
Right now, I get an error in my terraform plan task:
```
Error: Failed to get the data key required to decrypt the SOPS file.
https://mykeyvaultname.vault.azure.net/keys/sops-enc-key/<guid>: FAILED
Please run 'az login' to setup account.
```

**Comment by mericstam** [comment]
Hi, does it work when you run it on your local environment?

**Comment by tonswart** [comment]
Without any problems. The keyvault is configured with "Azure role-based access control" and the service connection account we use for the terraform task has the same RBAC rights as my personal account.

**Comment by tonswart** [comment]
On my local environment it's working because I'm logged in with az login.

**Comment by mericstam** [comment]
Hi, Sorry for late reply,
If I remember correctly you need authenticate with az login in the pipeline for this to work. 
You can create a shell task prior to the terraform tasks that does the az login with your service principal cerdentials. 
https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli#sign-in-with-a-service-principal

**Comment by mericstam** [comment]
Ok got it.  As you use AzureCLI@2 and it works,  the access rights should be ok for the service principal. 
 AzureCLI@2 uses az login under the hood to authenticate. [AzureCLI line 135]( https://github.com/microsoft/azure-pipelines-tasks/blob/39de17a0f52bb842e98e2b12b62b33d532255d23/Tasks/AzureCLIV2/azureclitask.ts#L135)
This task does not do az login but relies on terraform and the azurerm provider to authenticate by setting -backend-config more info: [azurerm provider](https://github.com/hashicorp/terraform-provider-azurerm).  So nothing I can fix within the Task
