### ISSUE TITLE
Terraform Plan - Output Variable - Missing jsonPlanFilePath

### ISSUE THREAD

**Issue by lupusllc** [microsoft/azure-pipelines-terraform#117]
When doing a Terraform plan in V2 we get an output variable for jsonPlanFilePath but not for V3. Information on this variable is also missing from the readme from V3.

I tried using -out and specifying a tfstate file to output to, but the results were the same with or without -out in V3. I also tried using Terraform show, but it just printed the results to the screen.

V3:
![image](https://user-images.githubusercontent.com/16469173/206321198-d844cfd1-cf89-4756-b6ed-0604f110437e.png)
![image](https://user-images.githubusercontent.com/16469173/206321244-189913c3-cd0e-4364-b6e1-2c26bda69eda.png)

V2:
![image](https://user-images.githubusercontent.com/16469173/206321817-722d5156-47ed-49f3-b536-573707ed560b.png)
![image](https://user-images.githubusercontent.com/16469173/206322002-99792c90-6181-474e-9cdb-d1dda4ddf419.png)

**Comment by mericstam** [comment]
closing this as a valid solution. feel free re-open if you diagree

**Comment by mericstam** [comment]
@DavidJFowler please refer to a closed issues rather the posting directly in it.  It will be a lot simpler for us to see a new issue the issue list. This time I will reopen it.

**Comment by mericstam** [comment]
no change between v3 and v4 other then updated version of the azure-pipelines-task-lib/task lib which is used for setting variables.  they where automatically set as output.  My guess is that azure-pipelines-task-lib/task, setVariable function has changed behavior.  I will take a look

**Comment by mericstam** [comment]
Looks like there was a bit of mix of the  setting of output variables. changed them all to output where they should.
