### ISSUE TITLE
Custom command is wrapped in quotation marks and not a recognisable terraform command

### ISSUE THREAD

**Issue by codeprang** [microsoft/azure-pipelines-terraform#125]
I'm trying to use the custom command to import a resource. If I enter a command such as:
`import aws_instance.example i-abcd1234`
into the Custom Command box in the task on the pipeline, it gets wrapped in quotation marks and the task fails as it isn't recognised as a valid terraform command. This can be seen in the logs as:

> _tool\terraform\1.3.7\x64\terraform.exe "import aws_instance.example i-abcd1234"

Some better documentation on how to use the custom command would also be helpful.

**Comment by mericstam** [comment]
Hi, Are you using classic pipeline or YAML pipeline?
In the custom field you should only put the command in your case:  import  .  in the commandOptions field you should put your  options, in your case: aws_instance.example i-abcd1234

**Comment by codeprang** [comment]
Thanks, that's fixed it now. I'm using the classic pipeline.
