### ISSUE TITLE
Terraform Import with index

### ISSUE THREAD

**Issue by Marquis79** [microsoft/azure-pipelines-terraform#132]
Hi,

Have you tried using the terraform plugin with the import command with an index on the resource like this:

- task: TerraformTaskV3@3
  displayName: 'Terraform import'
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    commandOptions: '--var-file myvarfile.tfvars azurerm_route_table.tr-tblroute["index"] /subscriptions/id/resourceGroups/rg/providers/Microsoft.Network/routeTables/tr-routetable'
    outputTo: 'console'
    customCommand: 'import'
    environmentServiceNameAzureRM: serviceName

Looks like the plugin doesn't allow putting an index on the option line?

Is it a bug?

thanks

**Comment by Marquis79** [comment]
More details about my tests :

commandOptions: '--var-file NPR.AZ.COMMUN.01.tfvars azurerm_route.tr-route["pr-svcpartage-commun-001"] ${{ parameters.resourceId }}'
output :
/usr/bin/terraform import --var-file NPR.AZ.COMMUN.01.tfvars azurerm_route.tr-route[pr-svcpartage-commun-001] ...
 Index brackets must contain either a literal number or a literal string.

If I add \" like this :
commandOptions: '--var-file NPR.AZ.COMMUN.01.tfvars azurerm_route.tr-route[\"pr-svcpartage-commun-001\"] ${{ parameters.resourceId }}'
output:
/usr/bin/terraform import --var-file NPR.AZ.COMMUN.01.tfvars azurerm_route.tr-route[\pr-svcpartage-commun-001"] ...
the first " of the index has disappeared ans I dont know why

**Comment by AminTi** [comment]
Thanks for reporting, we will look into this and get back to you sooner.

**Comment by mericstam** [comment]
Hi.  Have you tried to escape the quotes?  like commandOptions: '--var-file myvarfile.tfvars azurerm_route_table.tr-tblroute[\"index\"]

**Comment by Marquis79** [comment]
Yes I have tried like this :
commandOptions: '--var-file NPR.AZ.COMMUN.01.tfvars azurerm_route.tr-route[\"pr-svcpartage-commun-001\"] ${{ parameters.resourceId }}'
and the output is :
usr/bin/terraform import --var-file NPR.AZ.COMMUN.01.tfvars azurerm_route.tr-route[\pr-svcpartage-commun-001"] ...
the first " of the index has disappeared

**Comment by mericstam** [comment]
ok. that is strange. let me look around and see what I can come up with.  I think the issue here is that  the extension use string input using another tool lib , azure-pipelines-task-lib/task, to parse the quotes ETC.

**Comment by mericstam** [comment]
Ok found another reported issue on azure-pipelines-task-lib.  that stated if you want literal "b" you should escape it like this "\\"b\\""
that would mean  commandOptions: '--var-file myvarfile.tfvars azurerm_route_table.tr-tblroute["\\"index\\""]

**Comment by Marquis79** [comment]
Nice! It works with the way you wrote the index:
["\\"index\\""]
Do you plan to correct this problem or I must thinking to write the " with the way you indicated to me?
Thanks!

**Comment by mericstam** [comment]
As this is not specific to the extension but rather behavior of the  azure-pipelines-task-lib we will not fix this.  I will however updated the documentation on escaping quotes.
