### ISSUE TITLE
Locks should be released when cancelling

### ISSUE THREAD

**Issue by quails4Eva** [microsoft/azure-pipelines-terraform#139]
Currently if a pipeline is cancelled during the Plan task it can leave a lock on the terraform state file which prevents further terraform tasks until someone manually breaks the lease. The task (and any other tasks that obtain locks) should attempt to relinquish all locks it's obtained when it receives a cancellation notice.

Using Azure backend, state in blob storage.

**Comment by mericstam** [comment]
duplicate #31
