### ISSUE TITLE
The process 'C:\hostedtoolcache\windows\terraform\1.4.6\x64\terraform.exe' failed with exit code 1

### ISSUE THREAD

**Issue by vaibhavkarade42** [microsoft/azure-pipelines-terraform#150]
We are getting error while running release pipeline for deploying Azure resources. Also terraform state file is not getting generated in mentioned storage account.

**Comment by mericstam** [comment]
Hi. To be able to assist you, please supply the log output.

**Comment by mericstam** [comment]
closing the due to inactive
