### ISSUE TITLE
terraform creating terraform-provider file in temp folder, how to remove via build pipeline run

### ISSUE THREAD

**Issue by manishlak** [microsoft/azure-pipelines-terraform#163]
using task to perform terraform
![image](https://github.com/microsoft/azure-pipelines-terraform/assets/100189919/05067a63-6de1-4417-a624-8b4859dc56b0)

after build pipeline complete will remain terraform-provider file left in agent machine
![image](https://github.com/microsoft/azure-pipelines-terraform/assets/100189919/3fba0869-1562-4dd1-bf0b-00af89501277)

how to remove via pipeline or manually only to be remove?
due to this agent machine drive is getting full

**Comment by mericstam** [comment]
Hi, thanks for reporting. We will take a look at this.

**Comment by stepintooracledba** [comment]
@mericstam 

Do we have an estimate on when this bug will be resolved?

@manishlak,

May I please know if this is sorted? Any workaround?

**Comment by mericstam** [comment]
After investigaing some: this is an issue with terraform CLI on windows machines 
https://github.com/hashicorp/terraform/issues/28477
So nothing to do with the extension code.
As a workaround I would delete the files with a separate script task after terraform deploy is done

br
Manuel

**Comment by stepintooracledba** [comment]
Thanks @mericstam for the confirmation.

**Comment by mericstam** [comment]
Closing this as it is not related to extension code.
