### ISSUE TITLE
Using the main.tfplan as an artifact in the release pipeline throws error

### ISSUE THREAD

**Issue by vineet-007** [microsoft/azure-pipelines-terraform#175]
I'm creating a terraform build and release pipeline, producing the main.tfplan build artifact in the terraform plan step. This tfplan file is to be consumed in the release pipeline, but it throws the below error.

<img width="524" alt="image" src="https://github.com/microsoft/azure-pipelines-terraform/assets/75297542/08dd86b6-0865-44f8-aae7-cb07732e732a">

I'm thinking there is conflict with the provider credentials issue between tfplan file and the service connection logic. Can anyone please help me with this ?

**Comment by mericstam** [comment]
Hi,
My guess is that the apply step can not find the main.tfplan file.  If you supply your YAML code or if you use classic pipelines take some images  of the ui of the pipeline so I can assist you.

BR

Manuel

**Comment by vineet-007** [comment]
Hey @mericstam, my issue is related to https://github.com/microsoft/azure-pipelines-terraform/issues/145. I can close this one for now if someone's working on it.
