### ISSUE TITLE
Feature Request: Terraform Refresh Command

### ISSUE THREAD

**Issue by gvee-uk** [microsoft/azure-pipelines-terraform#18]
I'd like a support for the `terraform refresh` command.

This would allow for separation of refresh logs from the `terraform plan` and `terraform apply` outputs.

Having the plan output separate from the refresh will remove significant noise on larger projects.

A typical workflow might look like this:

```bash
terraform init
terraform validate
terraform refresh
terraform plan -refresh=false -out=tfplan -no-color
terraform apply -auto-approve tfplan -no-color
```

**Comment by mericstam** [comment]
We are planning for a V3 release pretty soon with support for custom command, in theory means all commands terraform supports,  and cleaner execution for the existing ones. Still in development.

**Comment by tds-talent** [comment]
Would you accept a contribution for this feature before V3?

I pulled the code last night and the changes don't look too tricky (though I couldn't find instructions on running the tests).

**Comment by gvee-uk** [comment]
Would you accept a contribution for this feature before V3?

I pulled the code last night and the changes don't look too tricky (though I couldn't find instructions on running the tests).

**Comment by mericstam** [comment]
In theory, yes I would accept it, but since we are working on V3 already and don't have a lot of  people working on things, review  and test of your potential contribution might be after V3 release . You are most welcome to contribute but we can not guarantee release date before V3.

**Comment by mericstam** [comment]
Hi, V3 release is out in version 0.1.17 on the Marketplace. You could use the custom command option to use refresh.

**Comment by gvee-uk** [comment]
This is brilliant. Upgraded the task today and now have a really tidy `plan` output as the `refresh` has been split in to an earlier task. Thank you for the update @mericstam !
