### ISSUE TITLE
Unable to Configure Definition Parameters in Set Definition

### ISSUE THREAD

**Issue by ASHR4** [microsoft/azure-pipelines-terraform#183]
Hi Guys,

Trying to configure the diagnostic settings for KeyVault which is in the Deploy-Diagnostics-LogAnalytics set definition; [link](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/79aefacd3250d9616fb21e4c9709e43526e32cc0/modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_diagnostics_loganalytics.tmpl.json#L1443-L1450)

The only parameters which allows me to configure for the KeyVault are [these](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/79aefacd3250d9616fb21e4c9709e43526e32cc0/modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_diagnostics_loganalytics.tmpl.json#L1443-L1450) despite the definition supports:

- effect
- profileName
- logAnalytics
- metricsEnabled
- logsEnabled
- matchWorkspace

Am I being silly in trying to configure these or does this module not support this at the moment, if so can you add this functionality?

**Comment by mericstam** [comment]
Hi, This has nothing to do with the actual extension for terraform in Azure DevOps. 
If you think it does please provide the error you get from the pipeline log.

Br
Manuel
