### ISSUE TITLE
Warning!!! TerraformTaskV4@4 shows oidc_token  as plain Text

### ISSUE THREAD

**Issue by Mousling1992** [microsoft/azure-pipelines-terraform#191]
## Description
I am using the `TerraformTaskV4@4` task in Azure DevOps to manage my resources. However, I've noticed that the token is not being masked in the logs like the client_id or the tenant_id, which poses a security risk.

## Steps to Reproduce
1. Step 1: Login with AzureCli
2. Step 2: Install terraform 1.5.7 on the Agent
3. use the TerraformTaskV4@4 to run terraform init
4. Go to Raw Logs in the Pipeline Run and there the -backend-config=oidc_token is written in plain text.

## Expected Behavior
The token should be masked in the logs to prevent exposure of sensitive information.

## Actual Behavior
The token is written in plain text.

**Comment by Mousling1992** [comment]
![image](https://github.com/microsoft/azure-pipelines-terraform/assets/96351261/09bd6f80-3a6a-43de-b2bb-5dbfcc774b25)
Please take this seriously

**Comment by mericstam** [comment]
Hi, Thanks for reporting. I will take a look at the problem.

**Comment by TheVexy** [comment]
<img width="904" alt="image" src="https://github.com/microsoft/azure-pipelines-terraform/assets/36013759/a16aae69-9d8c-45fd-96b9-12009c058a53">
I confirm

**Comment by mericstam** [comment]
HI, Just waiting for a review, then a brief regression test. Hopefully fix will be deployed today

**Comment by jessehouwing** [comment]
This warrants a self-published advisory on GitHub I suppose:

https://github.com/microsoft/azure-pipelines-terraform/security

@Mousling1992 please next time use the security reporting guidance to publish security issues that way there is a more coordinated response and it will automatically signal more of the right people to take immediate action.
