### ISSUE TITLE
Can we Authenticate using Service principle and Certificate instead of service connection in terraform task

### ISSUE THREAD

**Issue by sudhir-ops** [microsoft/azure-pipelines-terraform#200]
Can we Authenticate using Service principle and Certificate instead of service connection in terraform task

The below link says we can do it through PowerShell command. But is it possible in terraform task in azure pipeline.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_certificate

<img width="432" alt="image" src="https://github.com/microsoft/azure-pipelines-terraform/assets/55252751/7a9b5ee1-4a3a-416b-a28f-32d1fda1b87f">

**Comment by jaredfholgate** [comment]
Hi @sudhir-ops. If you don't want to use Service Connection authentication (why wouldn't you?), then you don't need the task. Just use the Terraform CLI directly and supply the env vars. You can still use the task to install terraform, but you don't need it for init, plan or apply if not using a service connection.
