### ISSUE TITLE
TerraformInstaller@1 fails with ambiguous identifier

### ISSUE THREAD

**Issue by fheinonen** [microsoft/azure-pipelines-terraform#205]
Using the TerraformInstaller@1 fails with the following error
```Encountered error(s) while parsing pipeline YAML:
Job Build: Step  task reference is invalid. The task name TerraformInstaller is ambiguous. Specify one of the following identifiers to resolve the ambiguity: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller, charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller

**Comment by mericstam** [comment]
it is because you have two extensions that have the same tasktames. either reference by full name or remove one or the other.
br
Manuel

**Comment by fheinonen** [comment]
Why does this issue happen, haven't seen this any other tasks?

**Comment by fheinonen** [comment]
The original issue I was trying to solve was that the ubuntu-latest image gave me different terraform versions plan and deploy.

**Comment by mericstam** [comment]
Hi. ambiguous names can occur because different extensions can have the same task names. extension names have to unique but not the underlying tasks. The same can happen when you reference different third party libraries from different sources. I would say it is pretty common.
