### ISSUE TITLE
Pipeline not parsing quotes correctly

### ISSUE THREAD

**Issue by mmyers299** [microsoft/azure-pipelines-terraform#21]
When passing a quoted string to TerraformTaskV2@2 the first \" becomes just a \ instead of a double quote. This only happen with the first \" passed to the task. Any additional once seem to be replaced correctly. 

I found a work around, if you pass "\" where you want the first double quote to be it works.

The first attachment shows the arguments being passed in correctly then transformed without the leading double quote, second one shows it being sent in with the "\" 

![passed as documented](https://user-images.githubusercontent.com/10511114/138890377-07e735b2-fd62-4463-8cd7-1b0d5d7030ff.PNG)
![passed in functional way](https://user-images.githubusercontent.com/10511114/138892618-2d2ffb3b-93b1-4568-a091-c9cdcb94556d.PNG)

**Comment by desolat** [comment]
Hey, could someone have a look into this please? Really annoying bug.

**Comment by Marquis79** [comment]
I have the same problem with the import command. I cannot use " on the options line.
I opened an issue on this (#132)
Do you have a solution to this problem?

**Comment by mericstam** [comment]
this by design how the azure-pipelines-task-lib/task  getInput works.  
escape as follows.   if you want pass literal "a"  to input you need to pass  "\"a\""
