### ISSUE TITLE
Error installing extension from marketplace

### ISSUE THREAD

**Issue by ahallEHP** [microsoft/azure-pipelines-terraform#211]
My org can't install the extension from the marketplace due to AAD error. 

Error: GetUserAccessToken: Failed to obtain an access token of identity

Activity ID: 73ff8f9d-afb2-4efd-98c2-14b789e93286
Date and Time: 2/12/2024 3:13:59 PM (UTC)

**Comment by mericstam** [comment]
Hi, sorry for late reply. Do you still have install issues?
Br
Manuel

**Comment by ahallEHP** [comment]
No, we had a naming conflict with an existing extension that was removed by Microsoft and then re-enabled during the installation process. After removing the existing extension the installation started working.
