### ISSUE TITLE
Add support for state command

### ISSUE THREAD

**Issue by roryprimrose** [microsoft/azure-pipelines-terraform#22]
I have sensitive state stored in an Azure storage account. The only process that has access to that state are the agents in a vm scale set via a service connection that is used in an AzDO pipeline run. We need to take actions against that state such as `list`, `mv` and `rm`.

**Comment by HenrikSommer-eng** [comment]
Where are the new repo location?

**Comment by mericstam** [comment]
https://github.com/microsoft/azure-pipelines-terraform

**Comment by HenrikSommer-eng** [comment]
ah so this is the new repo :)

**Comment by emersion-uday** [comment]
Can we expect support for state command anytime soon?

**Comment by mericstam** [comment]
Hi, I needed to rework some things after our internal review. Working on a internal release test today. hopefully all is well and public release will be done beginning of next week.

**Comment by emersion-uday** [comment]
@mericstam Thanks for quick reply. Hope everything will go well and release would be available ASAP!
By the way yesterday I found the alternate way for any terraform command the following is an example:

```
powershell: |
    terraform state list
    terraform state rm data.azuread_application.example
  workingDirectory:  "$(Build.SourcesDirectory)/Build/path/to/Terraform/files"
  displayName: Update Terraform State
```
