### ISSUE TITLE
Upgrade Node10 executor to Node16

### ISSUE THREAD

**Issue by phynot** [microsoft/azure-pipelines-terraform#221]
Microsoft has begun to remove Node10 from pipelines-* Agent packages

https://learn.microsoft.com/en-us/azure/devops/release-notes/2024/pipelines/sprint-238-update#node-10-removed-from-pipelines--agent-packages

This is the same issue as https://github.com/jason-johnson/azure-pipelines-tasks-terraform/issues/430

https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/migrateNode16.md

**Comment by mericstam** [comment]
Do you use v4 of the task? what error do you get?
we implemented support for node 16 already.

**Comment by phynot** [comment]
Thanks @mericstam for the prompt reply. I did not realize this work was done in https://github.com/microsoft/azure-pipelines-terraform/pull/130

FYI this was the error I was receiving on `TerraformTaskV3@3`

`##[error]This step requires a node version that does not exist in the agent filesystem. Path: /agent/externals/node10/bin/node`

After swapping to `TerraformTaskV4` I'm good to go.
