### ISSUE TITLE
Plan Issue with separate SCs for dev and prod environments

### ISSUE THREAD

**Issue by igor-teresco** [microsoft/azure-pipelines-terraform#237]
Our infra is separated in several subscriptions on same tenant and some resources are linked between them, like vnets. In ADO made 2 WIF-type SCs with Contributor role for their subscriptions - DevSC and ProdSC.

In main.tf we have 2 providers:
`provider "azurerm" {
  subscription_id = var.dev_subscription_id
  use_cli         = false
  use_oidc        = true
  tenant_id       = var.tenant_id
  client_id       = "DevSC"
  features {}
}

provider "azurerm" {
  alias           = "prod"
  subscription_id = var.prod_subscription_id
  use_cli         = false
  use_oidc        = true
  tenant_id       = var.tenant_id
  client_id       = "ProdSC"
  features {}
}`

In ADO pipeline I try to make terraform plan work:
' - task: TerraformTaskV4@4
          displayName: "Terraform Plan"
          env:
            TF_LOG: "TRACE"
          inputs:
            provider: "azurerm"
            command: "plan"
            workingDirectory: "$(System.DefaultWorkingDirectory)/dvs/environments/test"
            environmentServiceNameAzureRM: "ProdSC"
'
And it fails with:
'│ Error: building account: could not acquire access token to parse claims: clientCredentialsToken: received HTTP status 401 with response: {"error":"invalid_client","error_description":"AADSTS700213: No matching federated identity record found for presented assertion subject '***'. Please note that the matching is done using a case-sensitive comparison. Check your federated identity credential Subject, Audience and Issuer against the presented assertion. https://learn.microsoft.com/entra/workload-id/workload-identity-federation 
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on main.tf line 1, in provider "azurerm":
│    1: provider "azurerm" {
│ 
╵
╷
│ Error: building client: unable to obtain access token: clientCredentialsToken: received HTTP status 401 with response: {"error":"invalid_client","error_description":"AADSTS700213: No matching federated identity record found for presented assertion subject '***'. Please note that the matching is done using a case-sensitive comparison. Check your federated identity credential Subject, Audience and Issuer against the presented assertion. https://learn.microsoft.com/entra/workload-id/workload-identity-federation 
│ 
│   with provider["registry.terraform.io/hashicorp/azuread"],
│   on main.tf line 20, in provider "azuread":
│   20: provider "azuread" {
│ 
'

If I'll change SC here to DevSC - environmentServiceNameAzureRM: "ProdSC" plan will fail in 'prod' provider init...

Please advise if it is possible to use 2 separate WIF SCs in same run?

**Comment by mericstam** [comment]
Hi, thanks for your question.  
I don't think that is possible. @jaredfholgate Whats you take on it?

**Comment by jaredfholgate** [comment]
Hi. This is not possible, we only support a single service connection. I don't think this is possible outside of this task at this time either. This is a Terraform use case I have never come across, generally a single root module is scoped to a single identity. It defeats the point of trying to use two identities if they are both supplied to the same apply anyway, right?

It would be more usual to have a single identity with the relevant permissions across both subs for this use case, then more granular identities for the individual subscriptions. I would also question what the use case is for sharing networking configuration with Dev and Prod? Perhaps there is a more fundamental issue here?

**Comment by igor-teresco** [comment]
One of the use cases is VPN access, we use OpenVPN VMs deployed in Prod subscription and it's vnet has peerings with all vnets in other environments, created under Dev subscription.
So to make TF properly link resources between the environments, we use "data" resource to map them. That leads to the necessity of declaring separate azurerm providers (dev and prod).
And having a possibility to use separate SCs for subscriptions look more secure than having one SC with rights in all subscriptions, as for now.

**Comment by jaredfholgate** [comment]
For the hub networking use case, the ability to peer to the hub is generally controlled by the team responsible for the hub networks. 

The place to manage the peering is as part of your subscription vending / application landing zone process. You’ll need to handle ip address management, routing, etc anyway so best to leave that to the central team.

If you don’t want to use two provider blocks for the two way peering, you can use AzAPI which does not have the same single subscription limitation as azurerm.

We use the AzAPI provider in our Azure Verified Module for Virtual Networks: https://github.com/Azure/terraform-azurerm-avm-res-network-virtualnetwork/tree/main/modules/peering

Hope that helps in some way.

**Comment by jaredfholgate** [comment]
I’m closing this issue for now since the limitation is not specific to this task.
