### ISSUE TITLE
[TerraformV1] multiple providers not supported

### ISSUE THREAD

**Issue by tao-zhang** [microsoft/azure-pipelines-terraform#29]
I have provider configuration like this:

```
provider "azurerm" {
  subscription_id = "7fc00504-cef0-40d1-9923-0cb98ea33037"
  features {}
}

provider "azurerm" {
  alias           = "devops"
  subscription_id = "95dj317e-9222-4250-ba79-8a82384e3889"
  features {}
}
```

The second provider is also azurerm but in different subscription. I use this provider to create data source for querying. Current task only supports **one** `environmentServiceNameAzureRM` which is a service connection for terraform provider. So how to configure a second provider?

**Comment by aaron-lewis-insight** [comment]
The work around is to grant access for the SPN attached to the service connection the necessary rights in any additional subscriptions and then additional providers can be defined in TF with different subscriptions.

**Comment by mericstam** [comment]
Hi it will work if you add :  

```code
provider "azurerm" {
  alias           = "devops"
  subscription_id = "95dj317e-9222-4250-ba79-8a82384e3889"
  tenant_id = "<your-tenant-id"
  client_id = "<your-client-id>"
  client_secret = "<your-secret>"
  features {}
}
```
