### ISSUE TITLE
service connection with managed identity not working

### ISSUE THREAD

**Issue by madhanbabu-be** [microsoft/azure-pipelines-terraform#35]
When we are using service connection with managed identity in the terraform,   init is failed because client_id and client_secret sent as undefined

terraform init -backend-config=storage_account_name=devopsterraformstatefile -backend-config=container_name=terraformstatefile -backend-config=key=iotdevsubscription.tfstate -backend-config=resource_group_name=AzureDevOps -backend-config=subscription_id= -backend-config=tenant_id= -backend-config=client_id=undefined -backend-config=client_secret=undefined

**Comment by mericstam** [comment]
Hi, Managed identity is currently not supported. I will look into adding it in a future release.

**Comment by mericstam** [comment]
I think PR #42  could solve this issue.
