### ISSUE TITLE
Too many command line arguments. Configuration path expected - While running simple TF plan

### ISSUE THREAD

**Issue by geborgeson** [microsoft/azure-pipelines-terraform#38]
We started seeing this error for the terraform plan within our orgs pipelines. It seems to have started happening with this PR was merged

https://github.com/microsoft/azure-pipelines-terraform/pull/36

```
/opt/hostedtoolcache/terraform/0.12.31/x64/terraform plan undefined -detailed-exitcode
Too many command line arguments. Configuration path expected.
##[error]Error: Terraform Plan failed with exit code: 1
Finishing: Terraform : plan
```

**Comment by glenak1911** [comment]
I'm also experiencing this error, and our pipelines are failing on the terraform plan step.

**Comment by geborgeson** [comment]
I was able to resolve this by adding -out=tfplan to the commandOptions parameter. Maybe a default option was updated

**Comment by glenak1911** [comment]
Thanks that worked for me!

**Comment by aquam8** [comment]
We skipped the `plan` phase and move to `apply` directly, that unblocked us for now - not ideal tho.

We do not use OUT file tho for `plan` so it would be good that this option is not made mandatory, thanks!

**Comment by mericstam** [comment]
Hi, I wil take a look at the problem
