### ISSUE TITLE
Allow for terraform tool installer to pull "required_version" from configuration files 

### ISSUE THREAD

**Issue by alexgagnon** [microsoft/azure-pipelines-terraform#40]
Hi, I'm wondering if there's a way to have the Terraform Tool Installer task pull the "required_version" field from configuration, instead of having to explicitly set it in the task?

**Comment by mericstam** [comment]
Hi, I guess you could use a variable in your pipeline, and in a step before the Installer task set the variable with what you got in a configuration.  look at: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/set-variables-scripts?view=azure-devops&tabs=bash

**Comment by mericstam** [comment]
Something like this might work if your terraform block uses this format ex.  required_version = "~> 0.12.29"  
yaml:
```yaml
- task: PowerShell@2
  name: setVersion
  inputs:
    targetType: 'inline'
    script: |
      $version = (((Select-String -Path <PathToTerraformFile> -Pattern "required_version").ToString()).split("="))[1].trim(' "~>')
      Write-Host "##vso[task.setvariable variable=terraform-version;isoutput=true]$version"

- task: TerraformInstaller@0
  inputs:
    terraformVersion: "$(setVersion.terraform-version)"
