### ISSUE TITLE
"Failed to Download task" errors

### ISSUE THREAD

**Issue by ccapellan** [microsoft/azure-pipelines-terraform#56]
Hi,

After the Terraform extension was updated to 0.1.16 on our on-prem Azure DevOps server, we've been seeing the attached error in the pipelines leveraging Terraform tasks:

##[warning]Failed to download task 'TerraformInstaller'. Error No task definition found matching ID a4789e5d-f6e8-431f-add9-379d640a883c and version 0.203.0. You must register the task definition before uploading the package.
##[warning]Back off 29.59 seconds before retry.
##[error]No task definition found matching ID a4789e5d-f6e8-431f-add9-379d640a883c and version 0.203.0. You must register the task definition before uploading the package.

**Comment by mericstam** [comment]
Hi @ccapellan, Have you tried to uninstall and then reinstall the extension? if not please try that. what version of Azure Devops server do you run?

**Comment by ccapellan** [comment]
Hi @mericstam The reinstallation worked; I'm now able to deploy.  Thanks for the suggestion!
