### ISSUE TITLE
Release pipeline is failing with terraform project template for azure devops -TerrafForm-DevOps

### ISSUE THREAD

**Issue by soundd2** [microsoft/azure-pipelines-terraform#59]
I have implemented Build pipeline and release pipeline using following lab link
https://azuredevopslabs.com/labs/vstsextend/terraform/ However it is failing at the release pipeline due to the following error
![image](https://user-images.githubusercontent.com/94822959/168754162-f9ebcf31-91b1-476e-a1c7-906c640409f8.png)
m�[31mError: �[0m�[0m�[1mFailed to get existing workspaces: Error creating storage client for storage account "terraformstoraged7d37c12": azure: malformed storage account key: illegal base64 data at input byte 0�[0m
Please assist.

**Comment by mericstam** [comment]
Hi, This error is not from something inside the extension itself. input value seems to be the issue.  My guess is that the storagekey is not properly populated.  You should ask in the discussion part in the end of the page at: https://azuredevopslabs.com/labs/vstsextend/terraform/

**Comment by soundd2** [comment]
HI Mericstam,

I am not getting response from them , what needs to be done,

**Comment by mericstam** [comment]
Hi, I am not able to assist with azuredevopslabs
