### ISSUE TITLE
V3 Not Available As a Task

### ISSUE THREAD

**Issue by UP932296** [microsoft/azure-pipelines-terraform#60]
Hi,

I was super keen to start using V3 since the PR was merged - I've reinstalled the marketplace extension but still have no way to reference the V3 task - Wondering if this was on purpose or I'm missing something obvious 

Thanks

![image](https://user-images.githubusercontent.com/72310905/169243032-c2c00c25-abad-44a0-be1b-fafc5ba7b659.png)

**Comment by mericstam** [comment]
Hi, The release was pending approval, should be deployed now. version should be 0.1.17
/Manuel

**Comment by UP932296** [comment]
Thanks @mericstam,

I certainly will if you're okay leaving this open for a couple days for me to try out

**Comment by UP932296** [comment]
First of all super nice work with enhancing the functionality of this task, really nice to use a task as dynamic as this

The only issue I have, which is my specific use case, which is to run:

```hcl
 terraform fmt --recursive --check
 ```
 
 It still checks the provider config which spits an error out - this does not fail the task unless the custom command fails - but wish it wouldn't check for a fmt cmdlet; especially if I'm formatting the entire codebase :)

**Comment by mericstam** [comment]
Not sure If understand what you mean or how you want it to work for you, Could you elaborate a bit more

**Comment by UP932296** [comment]
Apologies - So for the specific task of terraform fmt --recursive --check I am running it from my root directory and not a specific directory where any config files are - When running the command it outputs:

```shell
/usr/local/bin/terraform providers
╷
│ Error: No configuration files
│ 
│ The directory /home/vsts/work/1/s contains no Terraform configuration
│ files.
╵

/usr/local/bin/terraform fmt --recursive --check
```

It's not breaking anything it's just an error I wasn't expecting to see

**Comment by mericstam** [comment]
ok, now I understand.  BTW please try with single dashes, not sure it will make difference, but terraform manual for fmt uses singles. https://www.terraform.io/cli/commands/fmt#usage
so command options would be:
`-recursive -check`

**Comment by mericstam** [comment]
Ok I think I found the error, the custom command runs the function warnIfMultipleProviders, which make sense for plan and apply but not for recursive fmt..  I will ad a conditional for it or perhaps just remove it for custom

**Comment by mericstam** [comment]
decided to remove it, fixed in PR #61.  Will deploy it as soon as it gets approved

**Comment by UP932296** [comment]
> ok, now I understand. BTW please try with single dashes, not sure it will make a difference, but terraform manual for fmt uses single. https://www.terraform.io/cli/commands/fmt#usage so command options would be: `-recursive -check`

Sorry just wrote it directly here and didn't check :)

**Comment by mericstam** [comment]
Thank you for helping out :)

**Comment by mericstam** [comment]
version 0.1.18 now deployed

**Comment by UP932296** [comment]
Just used it - works like a treat - thanks for sorting that :)
