### ISSUE TITLE
Terraform Plan/Apply unable to read state file from another subscription

### ISSUE THREAD

**Issue by slawchod** [microsoft/azure-pipelines-terraform#67]
Hi,

We have created central storage account in separated subscription to store state files in secure location. In single stage we have terraform init which is using service connection A to subscription A (for backend setup) and in next step we are having terraform plan or apply with service connection B to subscription B. Additionally SPN under B has rights to storage account from A.

Such setup was working for couple of months but after 25th of May (more or less) something has changed and we have started to get following errors on plan/apply.

`Error: Error loading state: Error retrieving keys for Storage Account "<storage_account_name>": storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group '<resource_group_name>' could not be found`

Init itself was successful all the time. There was no code change on our side. We even extended permissions for tests and we set Contributor for B SPN to entire A subscription but issue was the same.

The strange thing is that successful (prior issue) and failed steps have the same Terraform extension version: 0.0.142. We install Terraform version 0.12.3. 

We have some kind of workaround but it would require reconfiguration in many release pipelines and tens of commits. If you could revert change in extension it would be great. Thanks!

**Comment by mericstam** [comment]
The extension does not  currently  support having the state file in another subscription. Looking into what it would take to fix it

**Comment by mericstam** [comment]
So after a bit of tinkering I manage to have two different service connections for separate subscriptions.
Just as the original comment I have the 'init' command on one service connection where I have my state files.  `backendServiceArm: 'myStatesSPN'`
And on my 'plan' and 'apply' commands I set `environmentServiceNameAzureRM: 'myProdSPN'`
This way I have states and environments separated. The two different service connections are backed by totally different Azure Subs with separate AAD.
I would think you need one service connection for each subscription you wish to deploy towards. I only have two so I can't test deploy to multiple subs. 

example:
```bash
- task: TerraformTaskV3@3
      displayName: 'terraform init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'myStatesSPN'
        backendAzureRmResourceGroupName: 'terraform'
        backendAzureRmStorageAccountName: 'statestore'
        backendAzureRmContainerName: 'state'
        backendAzureRmKey: 'state.tfstate'

   - task: TerraformTaskV3@3
      name: plan
      displayName: 'terraform plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-out=tfplan'
        environmentServiceNameAzureRM: 'myProdSPN'
```

**Comment by slawchod** [comment]
I agree that MS fixed that in TerraformTaskV3@3

**Comment by danielcgonzalez** [comment]
for me this is not a valid solution, we should be able of using the same service principal, to store tfstate in different subscription, at least, if we could replace the backend data with container id, for example
