### ISSUE TITLE
how to use Hetzner hcloud provider

### ISSUE THREAD

**Issue by quadridevops** [microsoft/azure-pipelines-terraform#69]
I am not able to use hetzner hcloud provider using this Terraform plug in for azure devops.

Do you have any suggestions or work around.?

**Comment by mericstam** [comment]
Hi, as we do not currently support hetzner cloud, my suggestion would be to use only the TerraformInstaller task, and then use a script task to setup your backend and issue your terraform commands.

**Comment by quadridevops** [comment]
> Hi, as we do not currently support hetzner cloud, my suggestion would be to use only the TerraformInstaller task, and then use a script task to setup your backend and issue your terraform commands.

Hi Thank you for your response. Could you please provide any guide or link. I am able to use TerraformInstaller task but then not getting how to issue terraform commands after backend creation.

**Comment by mericstam** [comment]
Hi,
checkout terraform CLI tutorials at https://learn.hashicorp.com/collections/terraform/cli
and how to use script tasks in Azure DevOps:  
for windows: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/command-line?view=azure-devops&tabs=yaml.
Linux: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops
