### ISSUE TITLE
changesPresent is missing in V3

### ISSUE THREAD

**Issue by templafymek** [microsoft/azure-pipelines-terraform#77]
https://github.com/microsoft/azure-pipelines-terraform/blob/79290bf69bc67f288bfdbe318544b9a36a65a926/Tasks/TerraformTask/TerraformTaskV3/task.json#L297

**Comment by mericstam** [comment]
good find!
I will fix it asap

**Comment by templafymek** [comment]
How is the progress?

**Comment by mericstam** [comment]
i will try to get it done by end of friday. 
br
Manuel

**Comment by mericstam** [comment]
PR created. waiting for review.  will have to wait until after the weekend until reviewed

**Comment by templafymek** [comment]
Review done :)
