### ISSUE TITLE
Terraform tool installer does not install latest version on hosted agent

### ISSUE THREAD

**Issue by KnutNiehaus** [microsoft/azure-pipelines-terraform#8]
The terraform tool installer does not install the latest version on a self hosted agent, output is:

```
(...)
2022-02-01T09:10:13.3133701Z Getting latest Terraform version.
2022-02-01T09:10:14.3695807Z Unable to get latest version: %s using 1.0.8
2022-02-01T09:10:14.3746273Z Downloading: https://releases.hashicorp.com/terraform/1.0.8/terraform_1.0.8_windows_amd64.zip
(...)
2022-02-01T09:10:27.7927297Z Your version of Terraform is out of date! The latest version
2022-02-01T09:10:27.7928079Z is 1.1.4. You can update by downloading from https://www.terraform.io/downloads.html
```
Input in version field ist "latest" 

YAML:

```
steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: 'Install Terraform latest'
```

worked as expected when a specific version is inserted:

YAML:

```
steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: 'Install Terraform 1.1.4'
  inputs:
    terraformVersion: 1.1.4
```

**Comment by mericstam** [comment]
@KnutNiehaus,  I moved to the new repo.  fix is done, a new release will be out as soon as testing is done

**Comment by alessiofilippin** [comment]
@mericstam hello

do you know if this release will also fix the issue with the backend configuration? 

I tried to run the Terraform install with the latest version,  but the init is failing with this error:
![image](https://user-images.githubusercontent.com/47082128/155173339-99e54481-206e-4034-9664-347b6bb7132d.png)

**Comment by mericstam** [comment]
Hi @alessiofilippin, Which version of the terraform task do you use?  TerraformTaskV1@0 or TerraformTaskV2@2?

**Comment by alessiofilippin** [comment]
yes, you are right - just tried now eheh

I was using an old version .. changed it to TerraformTaskV2@2 and the issue got fixed.

Thank you very much!

**Comment by mericstam** [comment]
@KnutNiehaus We are having some issues with deploy and test a forked PR, will try to solve together with my coworker asap.

**Comment by mericstam** [comment]
merged into main. Release pending

**Comment by mericstam** [comment]
@KnutNiehaus , version 0.1.14 of the extension is released
