### ISSUE TITLE
Changes Present Usage

### ISSUE THREAD

**Issue by ScratZa** [microsoft/azure-pipelines-terraform#86]
Hey sorry for the potentially silly question 

But how do you use the changes present output variable ? i dont see any way to give my task a reference in release pipelines ?

**Comment by ScratZa** [comment]
Ah i see the option to add a reference isnt available when the task is in a task group

**Comment by mericstam** [comment]
Hi, are still facing issues?

**Comment by maurice-freitag** [comment]
As far I can tell [this commit](https://github.com/microsoft/azure-pipelines-terraform/commit/c9f420149508fa4388fa6d156a66bd064df87e2d) should have fixed the issue but it's still unresolved for us. 

We're using the current extension version 0.1.18 which is a lot older than the commit :/ 
![image](https://user-images.githubusercontent.com/21076995/188155739-6174c344-feb7-4082-a160-94bda97b520e.png)

**Comment by maurice-freitag** [comment]
The extension has been updated to 0.1.19 this morning and the out variable is present for me 🥳

**Comment by mericstam** [comment]
I am closing this issue due to release of 0.1.19
