### ISSUE TITLE
Vsix file

### ISSUE THREAD

**Issue by oralcj** [microsoft/azure-pipelines-terraform#90]
Please how can I get the vsix file for this extension

**Comment by mericstam** [comment]
1. You go to this page. https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks
2. click button "get it free"
3. On the next page click download
![image](https://user-images.githubusercontent.com/3337673/191691408-1d85e06d-cba3-4b4c-94a7-e8f7fd436639.png)

**Comment by oralcj** [comment]
> 1. You go to this page. https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks
> 2. click button "get it free"
> 3. On the next page click download
>    ![image](https://user-images.githubusercontent.com/3337673/191691408-1d85e06d-cba3-4b4c-94a7-e8f7fd436639.png)

Thank you so much
