### ISSUE TITLE
We have multiple AWS service connections in our Azure DevOps project but none are listed in the Terraform release task?

### ISSUE THREAD

**Issue by kknd4eva** [microsoft/azure-pipelines-terraform#92]
As per the below image, despite us having AWS service connections with permissions to all pipelines (and in use in may places) they don't show up to be selected in any version of the Terraform release task? 

![2022-10-18 22_56_08-New release pipeline - Pipelines](https://user-images.githubusercontent.com/42256693/196423026-d1bea606-327a-45c3-aa13-f38e6939aec6.png)

**Comment by AminTi** [comment]
Thanks for reporting

**Comment by mericstam** [comment]
Hi, Trying to investigate a little. which type of AWS service connection do you use?  
![image](https://user-images.githubusercontent.com/3337673/196786298-76ddf256-ba2d-40e0-bb3f-54e373e15268.png)

**Comment by kknd4eva** [comment]
Hi, I think this can be closed. I was under the mistaken assumption you could use the standard service connection for the Terraform task. I see now you have to have a specific one for the Terraform tasks. I don't know if it's possible, but it would be nicer if you could just leverage your existing service connection(s) for these tasks.
