### ISSUE TITLE
Not able to find terraform tasks for confluent cloud provider in the Azure devops pipeline

### ISSUE THREAD

**Issue by dorasatis** [microsoft/azure-pipelines-terraform#95]
<img width="289" alt="Screenshot 2022-10-31 122838" src="https://user-images.githubusercontent.com/43595656/198949686-159234bc-68be-45e4-a947-72ce64ca5677.png">
<img width="221" alt="Screenshot 2022-10-31 121757" src="https://user-images.githubusercontent.com/43595656/198948075-68352eb2-2ab1-4676-acf5-fff17aecff9f.png">
We are trying to create new pipeline for confluent terraform tasks for automation in Azure devops yaml pipeline, but there is no confluent provider available under Terraform tasks. We can see only 3 providers (aws,azurerm & gcp). Please advise how could we find the confluent provider to fulfill our project requirement.
Also, we don't see confluent cloud in service connection under project settings to establish a connection from Azure devops.

**Comment by mericstam** [comment]
Unfortunatly there is no support for confluent cloud in the extension.
My suggestion is to use the terraform installer task and then use standard CLI tasks to issue the terraform commands needed.
